const axios = require('axios');
const { generateOTP, verifyOTP } = require('../src/utils/otpService'); // We might need to mock this or use API

const BASE_URL = 'http://localhost:5000/api';
const NUM_VOTERS = 500;

// Mock data generator
const generateVoter = (i) => ({
  reg_no: `REG${1000 + i}`,
  name: `Voter ${i}`,
  email: `voter${i}@example.com`,
  program: 'CS',
  status: 'ELIGIBLE'
});

const runLoadTest = async () => {
  console.log(`Starting Load Test with ${NUM_VOTERS} voters...`);
  const startTime = Date.now();
  let successCount = 0;
  let failCount = 0;

  // 1. Seed Voters (We assume they are already imported or we mock the import)
  // For this test, let's assume we are hitting the endpoints directly.
  
  // Actually, to test E2E, we need to:
  // 1. Request OTP
  // 2. Verify OTP -> Get Token
  // 3. Cast Vote

  // Since we can't easily read the console for OTP in a script without hooking stdout,
  // we might need a "backdoor" or just mock the OTP verification on server for test env.
  // OR, we can use the `otpStore` if we import it, but that's in-memory of the running server, not this script.
  
  // Workaround: We will use a special "test" OTP if configured, OR just simulate the API calls assuming we know the OTP logic.
  // Since we are using a mock OTP service that logs to console, we can't programmatically get it easily here.
  
  // ALTERNATIVE: We'll just hit the Vote endpoint directly if we can generate valid tokens?
  // No, tokens are generated by server.
  
  // Let's try to simulate the flow by modifying the server to accept a fixed OTP for a specific test user prefix?
  // Or better, for this load test, let's just assume we have a list of valid tokens.
  
  // REALISTIC APPROACH for this scope:
  // We will create a "seed" script that inserts voters and verifications directly into DB, getting tokens.
  // Then we use those tokens to vote concurrently.

  console.log('Please ensure you have seeded the database with voters and tokens first.');
  console.log('This script assumes tokens are available or we mock the flow.');
  
  // Let's implement a simplified version that just hits the public stats endpoint 500 times to test load?
  // No, requirement is "500 simulated voters".
  
  // Let's create a helper to seed DB with 500 voters and get their tokens.
  // But we can't easily access the running server's DB connection from here without importing prisma.
  
  const { PrismaClient } = require('@prisma/client');
  const prisma = new PrismaClient();
  const crypto = require('crypto');

  try {
    console.log('Seeding 500 test voters and tokens...');
    const tokens = [];
    
    // Batch create voters and tokens
    for (let i = 0; i < NUM_VOTERS; i++) {
      const voterData = generateVoter(i);
      
      // Create/Update Voter
      const voter = await prisma.eligibleVoter.upsert({
        where: { reg_no: voterData.reg_no },
        update: {},
        create: voterData,
      });

      // Create Verification/Token
      const ballotToken = crypto.randomBytes(32).toString('hex');
      const tokenHash = crypto.createHash('sha256').update(ballotToken).digest('hex');

      await prisma.verification.upsert({
        where: { voter_id: voter.id },
        update: { ballot_token: tokenHash, consumed_at: null },
        create: {
          voter_id: voter.id,
          otp_hash: 'test_verified',
          ballot_token: tokenHash,
          verified_at: new Date(),
          issued_at: new Date(),
        }
      });

      tokens.push(ballotToken);
    }
    console.log('Seeding complete. Starting voting phase...');

    // Fetch positions to vote for
    const positions = await prisma.position.findMany({
      include: { candidates: true }
    });

    if (positions.length === 0) {
      throw new Error('No positions found. Please create positions first.');
    }

    // Execute votes concurrently
    const votePromises = tokens.map(async (token, index) => {
      try {
        // Randomly select a candidate for the first position
        const position = positions[0];
        const candidate = position.candidates[Math.floor(Math.random() * position.candidates.length)];

        await axios.post(`${BASE_URL}/vote`, {
          votes: [{ position_id: position.id, candidate_id: candidate.id }]
        }, {
          headers: { Authorization: `Bearer ${token}` }
        });
        successCount++;
      } catch (error) {
        // console.error(`Vote failed for voter ${index}:`, error.message);
        failCount++;
      }
    });

    await Promise.all(votePromises);

    const duration = (Date.now() - startTime) / 1000;
    console.log(`Load Test Complete in ${duration}s`);
    console.log(`Successful Votes: ${successCount}`);
    console.log(`Failed Votes: ${failCount}`);
    console.log(`Throughput: ${NUM_VOTERS / duration} votes/sec`);

  } catch (error) {
    console.error('Load Test Error:', error);
  } finally {
    await prisma.$disconnect();
  }
};

runLoadTest();
